### ISSUE TITLE
BLM Fire III Procs

### ISSUE THREAD

**Issue by abandon-the-flesh** [StackBLU/UltimateCombo#1]
Fire III procs are getting dropped. At the end of the ice phase, if a F3 proc from paradox in AF is active, its optimal to transpose then use F3 procs to start the rotation over. Otherwise, it should be used in AF before it expires. You could potentially set this as a movement option in AF. Manually transposing with the expectation to use this proc at the end of AI defaults the action to F4. This would work for me if I had the option to make F3 static, or if you added the option to not include it in the single target rotation.

Thanks.

**Comment by StackBLU** [comment]
Fixed and pushed! Thanks for helping out!
