### ISSUE TITLE
DRG (90) No Fang and Claw rotation

### ISSUE THREAD

**Issue by abandon-the-flesh** [StackBLU/UltimateCombo#3]
Not the biggest deal since its only lvl 90 I guess; -  but half the rotation just isn't being executed?

https://www.fflogs.com/reports/a:dmx2jCHXLaNQtcM1#fight=last&type=casts&source=2

1 True Thrust
0 Vorpal Thrust
0 Heavens Thrust
0 Fang and Claw

It just goes right back into disembowel and clips chaotic spring at 13 seconds or so (2.45gcd). Maybe it's looking for Lance Barrage? (upgrade of Vorpal Thrust at 96) I kept moving for positionals and was so confused.

**Comment by StackBLU** [comment]
Fixed and will appear in next update 👍  Thanks for bringing this up!
